Fixed a bug on downloading older versions of extensions. Implemented commands to exit the select_version prompt. Some minor bug fixes.

diff --git a/gnome-shell-extension-installer b/gnome-shell-extension-installer
--- a/gnome-shell-extension-installer
+++ b/gnome-shell-extension-installer
@@ -53,7 +53,7 @@ install_version() {
 
 select_version() {
     unset SELECTED_VERSION
-    while [ ! "$SELECTED_VERSION" ]; do
+    while [[ ! "$SELECTED_VERSION" ]]; do
         echo -n $1"Type a version to install: "
         if [ ! $SKIP_PROMPTS ]; then
             read INPUT
@@ -61,11 +61,13 @@ select_version() {
                 [ "$INPUT" == "$VERSION" ] &&
                 SELECTED_VERSION="$INPUT"
             done
+            [[ ! "$SELECTED_VERSION" ]] &&
+            echo "Available versions: ${EXTENSION_VERSIONS[@]}"
         else
             echo "${EXTENSION_VERSIONS[0]}"
             SELECTED_VERSION="${EXTENSION_VERSIONS[0]}"
         fi
-        echo "Available versions: ${EXTENSION_VERSIONS[@]}"
+        [[ "$INPUT" =~ (q|quit|exit) ]] && return 1
     done
 }
 
@@ -79,7 +81,7 @@ get_other_version() {
     echo
     [ "$SELECTED_VERSION" ] &&
     check_version_validation &&
-    install_version "$1" "$SELECTED_VERSION"
+    install_version "$EXTENSION_INFO" "$SELECTED_VERSION"
 }
 
 enable_extension() {
@@ -170,10 +172,13 @@ interactive_search() {
     while [ ! "$EXIT" ]; do
         echo -n "Enter a command: "
         read COMMAND
-        if [[ $COMMAND =~ ^([0-9] )+$ ]]; then
-            for n in "$COMMAND"; do
+        if [[ $COMMAND =~ ^[0-9]+( |[0-9])*$ ]]; then
+            for n in $COMMAND; do
                 if extract_info "${EXTENSIONS_QUERY[$n]}" && [ $n -lt $TOTAL ]; then
+                    [[ ${#EXTENSION_VERSIONS[@]} == 1 ]] &&
+                    SELECTED_VERSION="${EXTENSION_VERSIONS[@]}" ||
                     select_version "[$EXTENSION_NAME] "
+                    [ "$SELECTED_VERSION" ] &&
                     install_version "${EXTENSIONS_QUERY[$n]}" "$SELECTED_VERSION"
                 else
                     echo "[$n] Invalid extension number" >&2
@@ -181,7 +186,7 @@ interactive_search() {
             done
         elif [[ $COMMAND =~ ^d([0-9 ])+$ ]]; then
             for n in ${COMMAND:1}; do
-                if [ $n -lt $TOTAL ]; then
+                if [[ $n -lt $TOTAL ]]; then
                     extract_info "${EXTENSIONS_QUERY[$n]}"
                     echo -e "[$EXTENSION_NAME]"
                     echo -e "$EXTENSION_DESCRIPTION"
@@ -191,7 +196,7 @@ interactive_search() {
             done
         elif [[ $COMMAND =~ ^l([0-9 ])+$ ]]; then
             for n in ${COMMAND:1}; do
-                if [ $n -lt $TOTAL ]; then
+                if [[ $n -lt $TOTAL ]]; then
                     extract_info "${EXTENSIONS_QUERY[$n]}" &&
                     echo "[$EXTENSION_NAME] $EXTENSIONS_SITE$EXTENSION_LINK" ||
                     echo "[$n] Invalid extension number" >&2
@@ -199,8 +204,9 @@ interactive_search() {
                     echo "[$n] Invalid extension number" >&2
                 fi
             done
-        elif [[ $COMMAND =~ ^p([0-9 ])+$ ]]; then
-            if [ ${COMMAND:1} -le $PAGES ]; then
+        elif [[ $COMMAND =~ ^p( )*[0-9]+$ ]]; then
+            PAGE="$( echo ${COMMAND:1} | sed 's/^0*//' )"
+            if [[ $PAGE -le $PAGES ]]; then
                 PAGE_NUM="${COMMAND:1}"
                 echo "[$SEARCH_STRING] Obtaining page $PAGE_NUM"
                 download_info "/extension-query/?search=$SEARCH_STRING&page=$PAGE_NUM" \
@@ -209,7 +215,7 @@ interactive_search() {
                               "Failed to obtain page info" &&
                 load_content
             else
-                echo "[${COMMAND:1}] Invalid page number" >&2
+                echo "[$PAGE] Invalid page number" >&2
             fi
         elif [[ $COMMAND =~ ^(h|help)$ ]]; then
             search_help
@@ -264,7 +270,7 @@ DOWNLOAD_PARAMETERS="-Lfs"
 EXTENSIONS_SITE="https://extensions.gnome.org"
 EXTENSIONS_PATH="$HOME/.local/share/gnome-shell/extensions"
 
-PAGE=-1
+PAGES=-1
 TOTAL=-1
 
 COUNTER="$#"
