Added a option to save extensions from the search shell.

diff --git a/gnome-shell-extension-installer b/gnome-shell-extension-installer
--- a/gnome-shell-extension-installer
+++ b/gnome-shell-extension-installer
@@ -4,7 +4,7 @@
  #                                                                         #
  #                     GNOME Shell Extension Installer                     #
  #                                                                         #
- #   Version: 1.3.4 (31/03/2015)                                           #
+ #   Version: 1.3.5 (05/05/2015)                                           #
  #   Author: Ian Brunelli <ian@brunelli.me>                                #
  #   URL: https://github.com/ianbrunelli/gnome-shell-extension-installer   #
  #                                                                         #
@@ -38,16 +38,46 @@ check_version_validation() {
       echo -e "\nThe extension version validation has been disabled."; }
 }
 
+enable_extension() {
+    ENABLED_EXTENSIONS=$( gsettings get org.gnome.shell enabled-extensions |
+                          cut -f 1 -d "[" --complement )
+    [ "$( grep -v "$2" <<< "$ENABLED_EXTENSIONS" )" ] &&
+    { echo "[$1] Enabling extension"
+      [[ ${ENABLED_EXTENSIONS%?} ]] && SEPARATOR=", "
+      gsettings set org.gnome.shell enabled-extensions "[${ENABLED_EXTENSIONS%?}$SEPARATOR'$2']" &&
+      echo "[$1] Extension enabled (you may have to restart GNOME Shell)"; } ||
+    echo "[$1] The extension is already enabled"
+}
+
+extract_extension() {
+    mkdir -p "$EXTENSIONS_PATH/$2"
+    echo "[$1] Extracting extension"
+    unzip -qq -o "/tmp/shell-extension-install.$3.zip" -d "$EXTENSIONS_PATH/$2"
+    rm -f "/tmp/shell-extension-install.$3.zip"
+}
+
 install_version() {
+    extract_extension "$EXTENSION_NAME" "$EXTENSION_UUID" "$EXTENSION_ID" &&
+    enable_extension "$EXTENSION_NAME" "$EXTENSION_UUID"
+}
+
+move_file() {
+    mv "/tmp/shell-extension-install.$EXTENSION_ID.zip" "$EXTENSION_UUID.shell-extension.zip" 2> /dev/null &&
+    echo "[$EXTENSION_NAME] Extension saved as $EXTENSION_UUID.shell-extension.zip" ||
+    echo -e "\e[0;31mERROR\e[0m: Failed to save file" >&2
+    rm -f "/tmp/shell-extension-install.$EXTENSION_ID.zip"
+}
+
+download_version() {
     DOWNLOAD_TARGET=$( sed "s/^.*$2\": {\"pk[\": ]*\([^\"]*\),.*$/\1/" <<< "$1" )
     echo "[$EXTENSION_NAME] Downloading extension"
     if curl $DOWNLOAD_PARAMETERS -o "/tmp/shell-extension-install.$EXTENSION_ID.zip" \
             "$EXTENSIONS_SITE/download-extension/$EXTENSION_UUID.shell-extension.zip?version_tag=$DOWNLOAD_TARGET";
     then
-        extract_extension "$EXTENSION_NAME" "$EXTENSION_UUID" "$EXTENSION_ID" &&
-        enable_extension "$EXTENSION_NAME" "$EXTENSION_UUID"
+        return 0
     else
         echo -e "\e[0;31mERROR\e[0m: Failed to download extension" >&2
+        return 1
     fi
 }
 
@@ -62,7 +92,7 @@ select_version() {
     unset SELECTED_VERSION
     if [[ "${EXTENSION_VERSIONS[0]}" ]]; then
         while [[ ! $SELECTED_VERSION ]]; do
-           echo -n $1"Type a version to install: "
+           echo -n $1"Type a version to $2: "
            if [[ ! $SKIP_PROMPTS ]]; then
                read INPUT
                check_version_availability "$INPUT"
@@ -85,29 +115,12 @@ get_other_version() {
       for VERSION in ${EXTENSION_VERSIONS[@]}; do
           echo "- $VERSION"
       done
-      select_version; }
+      select_version "" "install"; }
     echo
     [ "$SELECTED_VERSION" ] &&
     check_version_validation &&
-    install_version "$EXTENSION_INFO" "$SELECTED_VERSION"
-}
-
-enable_extension() {
-    ENABLED_EXTENSIONS=$( gsettings get org.gnome.shell enabled-extensions |
-                          cut -f 1 -d "[" --complement )
-    [ "$( grep -v "$2" <<< "$ENABLED_EXTENSIONS" )" ] &&
-    { echo "[$1] Enabling extension"
-      [[ ${ENABLED_EXTENSIONS%?} ]] && SEPARATOR=", "
-      gsettings set org.gnome.shell enabled-extensions "[${ENABLED_EXTENSIONS%?}$SEPARATOR'$2']" &&
-      echo "[$1] Extension enabled (you may have to restart GNOME Shell)"; } ||
-    echo "[$1] The extension is already enabled"
-}
-
-extract_extension() {
-    mkdir -p "$EXTENSIONS_PATH/$2"
-    echo "[$1] Extracting extension"
-    unzip -qq -o "/tmp/shell-extension-install.$3.zip" -d "$EXTENSIONS_PATH/$2"
-    rm -f "/tmp/shell-extension-install.$3.zip"
+    download_version "$EXTENSION_INFO" "$SELECTED_VERSION" &&
+    install_version
 }
 
 extract_info() {
@@ -154,6 +167,7 @@ search_help() {
     echo -e "<number(s)>\tInstall extension(s)" \
             "\nd<number(s)>\tGet description(s)" \
             "\nl<number(s)>\tGet link(s) on extensions.gnome.org" \
+            "\ns<number(s)>\tSave the extension(s) on the current directory"\
             "\np<number>\tGo to page" \
             "\nr\t\tPrint the search content again" \
             "\nsn\t\tSort by name" \
@@ -197,9 +211,10 @@ interactive_search() {
                     SELECTED_VERSION="${EXTENSION_VERSIONS[@]}"
                     check_version_availability "$GNOME_VERSION"
                     [ "$SELECTED_VERSION" ] ||
-                    select_version "[$EXTENSION_NAME] "
+                    select_version "[$EXTENSION_NAME] " "install"
                     [ "$SELECTED_VERSION" ] &&
-                    install_version "${EXTENSIONS_QUERY[$n]}" "$SELECTED_VERSION"
+                    download_version "${EXTENSIONS_QUERY[$n]}" "$SELECTED_VERSION" &&
+                    install_version
                 else
                     echo "[$n] Invalid extension number" >&2
                 fi
@@ -227,6 +242,23 @@ interactive_search() {
                 else
                     echo "[$n] Invalid extension number" >&2
                 fi
+            done
+        elif [[ $COMMAND =~ ^s([0-9 ])+$ ]]; then
+            for n in $COMMAND; do
+                for n in ${COMMAND:1}; do
+                    if extract_info "${EXTENSIONS_QUERY[$n]}" && [ $n -lt $TOTAL ]; then
+                        [[ ${#EXTENSION_VERSIONS[@]} == 1 ]] &&
+                        SELECTED_VERSION="${EXTENSION_VERSIONS[@]}"
+                        check_version_availability "$GNOME_VERSION"
+                        [ "$SELECTED_VERSION" ] ||
+                        select_version "[$EXTENSION_NAME] " "download"
+                        [ "$SELECTED_VERSION" ] &&
+                        download_version "${EXTENSIONS_QUERY[$n]}" "$SELECTED_VERSION" &&
+                        move_file
+                    else
+                        echo "[$n] Invalid extension number" >&2
+                    fi
+                done
             done
         elif [[ $COMMAND =~ ^p( )*[0-9]+$ ]]; then
             PAGE="$( echo ${COMMAND:1} | sed 's/^0*//' )"
@@ -302,7 +334,8 @@ main_program() {
     { extract_info "$EXTENSION_INFO"
       check_version_availability "$1"
       if [ "$SELECTED_VERSION" ]; then
-          install_version "$EXTENSION_INFO" "$SELECTED_VERSION"
+          download_version "$EXTENSION_INFO" "$SELECTED_VERSION" &&
+          install_version
       else
           echo "[$EXTENSION_NAME] Extension not available for GNOME Shell $1"
           get_other_version "$1"
