Finished implemented update mode Fixes #8

diff --git a/gnome-shell-extension-installer b/gnome-shell-extension-installer
--- a/gnome-shell-extension-installer
+++ b/gnome-shell-extension-installer
@@ -50,17 +50,26 @@ enable_extension() {
 }
 
 extract_extension() {
+  [[ -f "$EXTENSIONS_PATH/$EXTENSION_UUID/metadata.json" ]] && CODE=7 || CODE=0
   mkdir -p "$EXTENSIONS_PATH/$2"
   echo "[$1] Extracting extension"
   unzip -qq -o "$TMP_DIR/shell-$SELECTED_VERSION-extension-install.$3.zip" -d "$EXTENSIONS_PATH/$2"
   rm -f "$TMP_DIR/shell-$SELECTED_VERSION-extension-install.$3.zip"
+  return $CODE
 }
 
 install_version() {
   [ "$INSTALL" == "download" ] && { move_file; return; }
-  extract_extension "$EXTENSION_NAME" "$EXTENSION_UUID" "$EXTENSION_ID" &&
-  enable_extension "$EXTENSION_NAME" "$EXTENSION_UUID" &&
-  INSTALLED+=("$EXTENSION_ID")
+  extract_extension "$EXTENSION_NAME" "$EXTENSION_UUID" "$EXTENSION_ID"
+  case "$?" in
+    0)
+      enable_extension "$EXTENSION_NAME" "$EXTENSION_UUID" &&
+      INSTALLED+=("$EXTENSION_ID")
+      ;;
+    7)
+      UPDATED+=("$EXTENSION")
+      ;;
+  esac
 }
 
 move_file() {
@@ -77,7 +86,7 @@ download_version() {
   { VERSION_TARGET=$( sed "s/^.*$2\": {\"pk[\": ]\+[0-9]\+[\", ]\+version[\": ]\+\([0-9]\+\)}.*$/\1/" <<< "$1" )
     VERSION_INSTALLED=$( sed -n "s/^[[:space:]]*\"version[\": ]\+\([0-9]\+\).*$/\1/p" "$METADATA_FILE" )
     [ $VERSION_TARGET -le $VERSION_INSTALLED ] &&
-    { if [ $UPDATE ]; then
+    { if [ $UPDATE_MODE ]; then
         echo "[$EXTENSION_NAME] The extension is up-to-date"
         return 2
       fi; } ||
@@ -402,7 +411,7 @@ get_info_from_id() {
   extract_info "$EXTENSION_INFO"
 }
 
-main_program() {
+get_extension() {
     check_version_availability "$1"
     { if [ "$SELECTED_VERSION" ]; then
         download_version "$EXTENSION_INFO" "$SELECTED_VERSION"
@@ -432,7 +441,7 @@ SCRIPT_NAME=$( basename "$0" )
 RESTART=0
 PAGES=-1
 TOTAL=-1
-unset INSTALL_ARRAY INSTALLED SEARCH_STRING SKIP_PROMPTS UPDATE
+unset INSTALL_ARRAY INSTALLED UPDATED SEARCH_STRING SKIP_PROMPTS UPDATE_MODE
 
 while [ $# -gt 0 ]; do
   if [[ $1 =~ ^-(h|-help)$ ]]; then
@@ -456,7 +465,7 @@ while [ $# -gt 0 ]; do
     INSTALL="download"
     shift
   elif [ "$1" == "--update" ]; then
-    UPDATE=1
+    UPDATE_MODE=1
     shift
   elif [ "$1" == "--restart-shell" ]; then
     if [[ "$XDG_SESSION_TYPE" == "wayland" ]]; then
@@ -503,17 +512,30 @@ if [[ -n ${SEARCH_STRING+ } ]]; then
 elif [ ${#INSTALL_ARRAY[@]} -gt 0 ]; then
   for EXTENSION in ${INSTALL_ARRAY[@]}; do
     get_info_from_id "$EXTENSION" &&
-    main_program "$GNOME_VERSION"
+    get_extension "$GNOME_VERSION"
   done
-elif [ $UPDATE ]; then
-  UPDATE_LIST=$( find -L "$EXTENSIONS_PATH" -maxdepth 2 -name "metadata.json" -exec \
-                      sed -n "s/^[[:space:]]*\"uuid[\": ]\+\(.*\)\".*$/\1/p" {} \; )
+elif [[ $UPDATE_MODE ]]; then
+  UPDATE_LIST=($( find -L "$EXTENSIONS_PATH" -maxdepth 2 -name "metadata.json" -exec \
+                       sed -n "s/^[[:space:]]*\"uuid[\": ]\+\(.*\)\".*$/\1/p" {} \; ))
   for EXTENSION in ${UPDATE_LIST[@]}; do
     IS_GIT_DIR=$( type git > /dev/null 2> /dev/null &&
                   git -C "$EXTENSIONS_PATH/$EXTENSION/" rev-parse --is-inside-work-tree 2> /dev/null )
-    if [ $IS_GIT_DIR ]; then
+    if [[ $IS_GIT_DIR ]]; then
       echo "[$EXTENSION] Updating from git"
-      git -C "$EXTENSIONS_PATH/$EXTENSION/" pull
+      GIT_UPDATE=$( LANG=en_US git -C "$EXTENSIONS_PATH/$EXTENSION/" pull )
+      case "$GIT_UPDATE" in
+        "Already up-to-date.")
+          echo "[$EXTENSION] The extension is up-to-date"
+          ;;
+        "")
+          echo -e "\e[0;31mERROR\e[0m: Failed to update extension (git exit code $?)" >&2
+          ;;
+        *)
+          echo "[$EXTENSION] Extension updated"
+          cat <<< "$GIT_UPDATE"
+          UPDATED+=("$EXTENSION")
+          ;;
+      esac
     else
       echo "[$EXTENSION] Searching extensions.gnome.org"
       download_info "/extension-query/?search=${EXTENSION}" \
@@ -521,20 +543,22 @@ elif [ $UPDATE ]; then
                     "The search page for \"$SEARCH_STRING\"" \
                     "Failed to obtain extension info" &&
       { IFS=$'\n' read -d '' -r -a EXTENSIONS_QUERY <<< "$( echo $EXTENSION_INFO | cut -f1 --complement -d"[" | sed 's/{[\"]*shell_version_map[\"]*:/\n/g' )"
-        FOUND=false
+        unset EXTENSION_INFO
         for SEARCH_RESULT in "${EXTENSIONS_QUERY[@]}"; do
           extract_info "$SEARCH_RESULT"
-          [[ "$EXTENSION" == "$EXTENSION_UUID" ]] && { FOUND=true; break; }
+          [[ "$EXTENSION" == "$EXTENSION_UUID" ]] &&
+          { EXTENSION_INFO="$SEARCH_RESULT"; break; }
         done
-        [ $FOUND ] && main_program "$GNOME_VERSION"; }
+        [[ $EXTENSION_INFO ]] && get_extension "$GNOME_VERSION"; }
     fi
   done
 else
   usage_guide
 fi
 
-if [ ${#INSTALLED[@]} -gt 0 ]; then
-  echo -n "${#INSTALLED[@]} extension(s) installed. "
+[[ ${#INSTALLED[@]} -gt 0 ]] && echo -n "${#INSTALLED[@]} new extension(s) installed. "
+[[ ${#UPDATED[@]} -gt 0 ]] && echo -n "${#UPDATED[@]} extension(s) updated. "
+if [[ ${#INSTALLED[@]} -gt 0 ]] || [[ ${#UPDATED[@]} -gt 0 ]]; then
   if [[ $RESTART == 1 ]]; then
     restart_shell
   elif [[ -n ${SEARCH_STRING+ } ]] && [[ "$XDG_SESSION_TYPE" != "wayland" ]]; then
